import { sql } from './config/db.js';

// Sample bank data based on your JSON structure
const bankData = [
  {
    id: 'agrani-bank',
    bankName: 'Agrani Bank PLC',
    bankType: 'State-Owned',
    establishedYear: 1972,
    headquarters: 'Dhaka',
    website: 'https://www.agranibank.org',
    totalBranches: 970,
    totalAtms: 1200,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 10,
        onlineBankingFee: 0,
        smsBankingFee: 15,
        debitCardFee: 200,
        creditCardFee: 500,
        nspbFee: 10,
        rtgsFee: 115,
        beftnFee: 5,
        checkbookFee: 50,
        statementFee: 20,
        otherCharges: 0,
        interestRate: 3.5,
      },
      {
        type: 'Current',
        minimumBalance: 5000,
        accountMaintenanceFee: 50,
        atmFeeOwn: 0,
        atmFeeOther: 15,
        onlineBankingFee: 0,
        smsBankingFee: 20,
        debitCardFee: 300,
        creditCardFee: 750,
        nspbFee: 15,
        rtgsFee: 125,
        beftnFee: 8,
        checkbookFee: 75,
        statementFee: 30,
        otherCharges: 25,
        interestRate: 0,
      },
      {
        type: 'FDR',
        minimumBalance: 25000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 0,
        onlineBankingFee: 0,
        smsBankingFee: 0,
        debitCardFee: 0,
        creditCardFee: 0,
        nspbFee: 0,
        rtgsFee: 0,
        beftnFee: 0,
        checkbookFee: 0,
        statementFee: 50,
        otherCharges: 0,
        interestRate: 5.5,
      }
    ]
  },
  {
    id: 'bangladesh-development-bank',
    bankName: 'Bangladesh Development Bank PLC',
    bankType: 'State-Owned',
    establishedYear: 1972,
    headquarters: 'Dhaka',
    website: 'https://www.bdbl.com.bd',
    totalBranches: 85,
    totalAtms: 120,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 12,
        onlineBankingFee: 0,
        smsBankingFee: 15,
        debitCardFee: 250,
        creditCardFee: 600,
        nspbFee: 12,
        rtgsFee: 120,
        beftnFee: 6,
        checkbookFee: 60,
        statementFee: 25,
        otherCharges: 0,
        interestRate: 3.5,
      }
    ]
  },
  {
    id: 'basic-bank',
    bankName: 'BASIC Bank Limited',
    bankType: 'State-Owned',
    establishedYear: 1988,
    headquarters: 'Dhaka',
    website: 'https://www.basicbanklimited.com',
    totalBranches: 450,
    totalAtms: 600,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 10,
        onlineBankingFee: 0,
        smsBankingFee: 15,
        debitCardFee: 200,
        creditCardFee: 500,
        nspbFee: 10,
        rtgsFee: 115,
        beftnFee: 5,
        checkbookFee: 50,
        statementFee: 20,
        otherCharges: 0,
        interestRate: 3.5,
      }
    ]
  },
  {
    id: 'janata-bank',
    bankName: 'Janata Bank PLC',
    bankType: 'State-Owned',
    establishedYear: 1972,
    headquarters: 'Dhaka',
    website: 'https://www.janatabank-bd.com',
    totalBranches: 915,
    totalAtms: 1100,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 12,
        onlineBankingFee: 0,
        smsBankingFee: 15,
        debitCardFee: 250,
        creditCardFee: 600,
        nspbFee: 12,
        rtgsFee: 120,
        beftnFee: 6,
        checkbookFee: 60,
        statementFee: 25,
        otherCharges: 0,
        interestRate: 3.5,
      },
      {
        type: 'Foreign Currency',
        minimumBalance: 500,
        accountMaintenanceFee: 100,
        atmFeeOwn: 0,
        atmFeeOther: 25,
        onlineBankingFee: 0,
        smsBankingFee: 30,
        debitCardFee: 500,
        creditCardFee: 1000,
        nspbFee: 50,
        rtgsFee: 200,
        beftnFee: 25,
        checkbookFee: 100,
        statementFee: 50,
        otherCharges: 50,
        interestRate: 1.0,
      }
    ]
  },
  {
    id: 'rupali-bank',
    bankName: 'Rupali Bank PLC',
    bankType: 'State-Owned',
    establishedYear: 1972,
    headquarters: 'Dhaka',
    website: 'https://www.rupalibank.org',
    totalBranches: 650,
    totalAtms: 800,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 10,
        onlineBankingFee: 0,
        smsBankingFee: 15,
        debitCardFee: 200,
        creditCardFee: 500,
        nspbFee: 10,
        rtgsFee: 115,
        beftnFee: 5,
        checkbookFee: 50,
        statementFee: 20,
        otherCharges: 0,
        interestRate: 3.5,
      },
      {
        type: 'DPS',
        minimumBalance: 500,
        accountMaintenanceFee: 25,
        atmFeeOwn: 0,
        atmFeeOther: 15,
        onlineBankingFee: 0,
        smsBankingFee: 20,
        debitCardFee: 0,
        creditCardFee: 0,
        nspbFee: 15,
        rtgsFee: 0,
        beftnFee: 8,
        checkbookFee: 0,
        statementFee: 30,
        otherCharges: 0,
        interestRate: 6.0,
      }
    ]
  },
  {
    id: 'sonali-bank',
    bankName: 'Sonali Bank PLC',
    bankType: 'State-Owned',
    establishedYear: 1972,
    headquarters: 'Dhaka',
    website: 'https://www.sonalibank.com.bd',
    totalBranches: 1220,
    totalAtms: 1500,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 10,
        onlineBankingFee: 0,
        smsBankingFee: 15,
        debitCardFee: 200,
        creditCardFee: 500,
        nspbFee: 10,
        rtgsFee: 115,
        beftnFee: 5,
        checkbookFee: 50,
        statementFee: 20,
        otherCharges: 0,
        interestRate: 3.5,
      },
      {
        type: 'Student',
        minimumBalance: 100,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 5,
        onlineBankingFee: 0,
        smsBankingFee: 10,
        debitCardFee: 100,
        creditCardFee: 0,
        nspbFee: 5,
        rtgsFee: 50,
        beftnFee: 3,
        checkbookFee: 25,
        statementFee: 10,
        otherCharges: 0,
        interestRate: 4.0,
      }
    ]
  },
  // Specialized Banks
  {
    id: 'bangladesh-krishi-bank',
    bankName: 'Bangladesh Krishi Bank',
    bankType: 'Specialized',
    establishedYear: 1973,
    headquarters: 'Dhaka',
    website: 'https://www.bkb.gov.bd',
    totalBranches: 1000,
    totalAtms: 500,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 500,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 8,
        onlineBankingFee: 0,
        smsBankingFee: 10,
        debitCardFee: 150,
        creditCardFee: 0,
        nspbFee: 8,
        rtgsFee: 80,
        beftnFee: 4,
        checkbookFee: 40,
        statementFee: 15,
        otherCharges: 0,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'probashi-kollyan-bank',
    bankName: 'Probashi Kollyan Bank',
    bankType: 'Specialized',
    establishedYear: 2010,
    headquarters: 'Dhaka',
    website: 'https://www.pkb.gov.bd',
    totalBranches: 65,
    totalAtms: 80,
    accountTypes: [
      {
        type: 'Expatriate Account',
        minimumBalance: 1000,
        accountMaintenanceFee: 50,
        atmFeeOwn: 0,
        atmFeeOther: 15,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 300,
        creditCardFee: 800,
        nspbFee: 20,
        rtgsFee: 150,
        beftnFee: 10,
        checkbookFee: 75,
        statementFee: 40,
        otherCharges: 25,
        interestRate: 4.5,
      }
    ]
  },
  {
    id: 'rajshahi-krishi-unnayan-bank',
    bankName: 'Rajshahi Krishi Unnayan Bank',
    bankType: 'Specialized',
    establishedYear: 1986,
    headquarters: 'Rajshahi',
    website: 'https://www.rakub.org.bd',
    totalBranches: 380,
    totalAtms: 200,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 500,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 8,
        onlineBankingFee: 0,
        smsBankingFee: 10,
        debitCardFee: 150,
        creditCardFee: 0,
        nspbFee: 8,
        rtgsFee: 80,
        beftnFee: 4,
        checkbookFee: 40,
        statementFee: 15,
        otherCharges: 0,
        interestRate: 4.0,
      }
    ]
  },
  // Private Commercial Banks
  {
    id: 'ab-bank',
    bankName: 'AB Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1982,
    headquarters: 'Dhaka',
    website: 'https://www.abbl.com',
    totalBranches: 110,
    totalAtms: 300,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 3000,
        accountMaintenanceFee: 75,
        atmFeeOwn: 0,
        atmFeeOther: 20,
        onlineBankingFee: 0,
        smsBankingFee: 30,
        debitCardFee: 400,
        creditCardFee: 1000,
        nspbFee: 20,
        rtgsFee: 150,
        beftnFee: 10,
        checkbookFee: 100,
        statementFee: 50,
        otherCharges: 25,
        interestRate: 4.0,
      },
      {
        type: 'NRB',
        minimumBalance: 1000,
        accountMaintenanceFee: 100,
        atmFeeOwn: 0,
        atmFeeOther: 25,
        onlineBankingFee: 0,
        smsBankingFee: 40,
        debitCardFee: 600,
        creditCardFee: 1500,
        nspbFee: 30,
        rtgsFee: 200,
        beftnFee: 15,
        checkbookFee: 150,
        statementFee: 75,
        otherCharges: 50,
        interestRate: 3.5,
      }
    ]
  },
  {
    id: 'bangladesh-commerce-bank',
    bankName: 'Bangladesh Commerce Bank Limited',
    bankType: 'Private Conventional',
    establishedYear: 1999,
    headquarters: 'Dhaka',
    website: 'https://www.bcbl.com',
    totalBranches: 65,
    totalAtms: 150,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2500,
        accountMaintenanceFee: 50,
        atmFeeOwn: 0,
        atmFeeOther: 18,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 350,
        creditCardFee: 900,
        nspbFee: 18,
        rtgsFee: 140,
        beftnFee: 9,
        checkbookFee: 90,
        statementFee: 45,
        otherCharges: 20,
        interestRate: 4.0,
      },
      {
        type: 'Women Account',
        minimumBalance: 1000,
        accountMaintenanceFee: 25,
        atmFeeOwn: 0,
        atmFeeOther: 15,
        onlineBankingFee: 0,
        smsBankingFee: 20,
        debitCardFee: 250,
        creditCardFee: 600,
        nspbFee: 15,
        rtgsFee: 120,
        beftnFee: 8,
        checkbookFee: 60,
        statementFee: 30,
        otherCharges: 0,
        interestRate: 4.5,
      }
    ]
  },
  {
    id: 'bank-asia',
    bankName: 'Bank Asia PLC',
    bankType: 'Private Conventional',
    establishedYear: 1999,
    headquarters: 'Dhaka',
    website: 'https://www.bankasia-bd.com',
    totalBranches: 150,
    totalAtms: 400,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2000,
        accountMaintenanceFee: 40,
        atmFeeOwn: 0,
        atmFeeOther: 16,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 300,
        creditCardFee: 800,
        nspbFee: 16,
        rtgsFee: 130,
        beftnFee: 8,
        checkbookFee: 80,
        statementFee: 40,
        otherCharges: 15,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'bengal-commercial-bank',
    bankName: 'Bengal Commercial Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 2000,
    headquarters: 'Dhaka',
    website: 'https://www.bcb.com.bd',
    totalBranches: 45,
    totalAtms: 120,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2500,
        accountMaintenanceFee: 60,
        atmFeeOwn: 0,
        atmFeeOther: 20,
        onlineBankingFee: 0,
        smsBankingFee: 30,
        debitCardFee: 400,
        creditCardFee: 1000,
        nspbFee: 20,
        rtgsFee: 150,
        beftnFee: 10,
        checkbookFee: 100,
        statementFee: 50,
        otherCharges: 25,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'brac-bank',
    bankName: 'BRAC Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 2001,
    headquarters: 'Dhaka',
    website: 'https://www.bracbank.com',
    totalBranches: 187,
    totalAtms: 650,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 3000,
        accountMaintenanceFee: 50,
        atmFeeOwn: 0,
        atmFeeOther: 20,
        onlineBankingFee: 0,
        smsBankingFee: 30,
        debitCardFee: 400,
        creditCardFee: 1000,
        nspbFee: 20,
        rtgsFee: 150,
        beftnFee: 10,
        checkbookFee: 100,
        statementFee: 50,
        otherCharges: 0,
        interestRate: 4.5,
      },
      {
        type: 'SME Account',
        minimumBalance: 10000,
        accountMaintenanceFee: 150,
        atmFeeOwn: 0,
        atmFeeOther: 25,
        onlineBankingFee: 50,
        smsBankingFee: 40,
        debitCardFee: 600,
        creditCardFee: 1500,
        nspbFee: 25,
        rtgsFee: 200,
        beftnFee: 15,
        checkbookFee: 150,
        statementFee: 75,
        otherCharges: 100,
        interestRate: 0,
      }
    ]
  },
  {
    id: 'citizens-bank',
    bankName: 'Citizens Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1983,
    headquarters: 'Dhaka',
    website: 'https://www.citizensbank.com.bd',
    totalBranches: 40,
    totalAtms: 100,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2000,
        accountMaintenanceFee: 45,
        atmFeeOwn: 0,
        atmFeeOther: 18,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 350,
        creditCardFee: 900,
        nspbFee: 18,
        rtgsFee: 140,
        beftnFee: 9,
        checkbookFee: 90,
        statementFee: 45,
        otherCharges: 20,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'city-bank',
    bankName: 'City Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1983,
    headquarters: 'Dhaka',
    website: 'https://www.thecitybank.com',
    totalBranches: 130,
    totalAtms: 350,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 5000,
        accountMaintenanceFee: 100,
        atmFeeOwn: 0,
        atmFeeOther: 25,
        onlineBankingFee: 0,
        smsBankingFee: 35,
        debitCardFee: 500,
        creditCardFee: 1200,
        nspbFee: 25,
        rtgsFee: 175,
        beftnFee: 15,
        checkbookFee: 125,
        statementFee: 60,
        otherCharges: 50,
        interestRate: 4.5,
      },
      {
        type: 'Premium Banking',
        minimumBalance: 100000,
        accountMaintenanceFee: 500,
        atmFeeOwn: 0,
        atmFeeOther: 0,
        onlineBankingFee: 0,
        smsBankingFee: 0,
        debitCardFee: 1000,
        creditCardFee: 2500,
        nspbFee: 0,
        rtgsFee: 0,
        beftnFee: 0,
        checkbookFee: 0,
        statementFee: 0,
        otherCharges: 0,
        interestRate: 5.0,
      }
    ]
  },
  {
    id: 'community-bank',
    bankName: 'Community Bank Bangladesh PLC',
    bankType: 'Private Conventional',
    establishedYear: 2013,
    headquarters: 'Dhaka',
    website: 'https://www.communitybankbd.com',
    totalBranches: 55,
    totalAtms: 120,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2000,
        accountMaintenanceFee: 40,
        atmFeeOwn: 0,
        atmFeeOther: 16,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 300,
        creditCardFee: 800,
        nspbFee: 16,
        rtgsFee: 130,
        beftnFee: 8,
        checkbookFee: 80,
        statementFee: 40,
        otherCharges: 15,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'dhaka-bank',
    bankName: 'Dhaka Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1995,
    headquarters: 'Dhaka',
    website: 'https://www.dhakabank.com.bd',
    totalBranches: 110,
    totalAtms: 280,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 3000,
        accountMaintenanceFee: 60,
        atmFeeOwn: 0,
        atmFeeOther: 20,
        onlineBankingFee: 0,
        smsBankingFee: 30,
        debitCardFee: 400,
        creditCardFee: 1000,
        nspbFee: 20,
        rtgsFee: 150,
        beftnFee: 10,
        checkbookFee: 100,
        statementFee: 50,
        otherCharges: 25,
        interestRate: 4.0,
      },
      {
        type: 'Student',
        minimumBalance: 500,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 10,
        onlineBankingFee: 0,
        smsBankingFee: 15,
        debitCardFee: 200,
        creditCardFee: 0,
        nspbFee: 10,
        rtgsFee: 80,
        beftnFee: 5,
        checkbookFee: 50,
        statementFee: 25,
        otherCharges: 0,
        interestRate: 4.5,
      }
    ]
  },
  {
    id: 'dutch-bangla-bank',
    bankName: 'Dutch-Bangla Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1996,
    headquarters: 'Dhaka',
    website: 'https://www.dutchbanglabank.com',
    totalBranches: 205,
    totalAtms: 5000,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2000,
        accountMaintenanceFee: 25,
        atmFeeOwn: 0,
        atmFeeOther: 15,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 250,
        creditCardFee: 750,
        nspbFee: 12,
        rtgsFee: 110,
        beftnFee: 6,
        checkbookFee: 75,
        statementFee: 30,
        otherCharges: 0,
        interestRate: 4.0,
      },
      {
        type: 'Salary',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 10,
        onlineBankingFee: 0,
        smsBankingFee: 20,
        debitCardFee: 200,
        creditCardFee: 500,
        nspbFee: 10,
        rtgsFee: 100,
        beftnFee: 5,
        checkbookFee: 50,
        statementFee: 25,
        otherCharges: 0,
        interestRate: 3.5,
      }
    ]
  },
  {
    id: 'eastern-bank',
    bankName: 'Eastern Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1992,
    headquarters: 'Dhaka',
    website: 'https://www.ebl.com.bd',
    totalBranches: 135,
    totalAtms: 400,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 3000,
        accountMaintenanceFee: 75,
        atmFeeOwn: 0,
        atmFeeOther: 22,
        onlineBankingFee: 0,
        smsBankingFee: 32,
        debitCardFee: 450,
        creditCardFee: 1100,
        nspbFee: 22,
        rtgsFee: 160,
        beftnFee: 12,
        checkbookFee: 110,
        statementFee: 55,
        otherCharges: 30,
        interestRate: 4.0,
      },
      {
        type: 'Premium Banking',
        minimumBalance: 50000,
        accountMaintenanceFee: 300,
        atmFeeOwn: 0,
        atmFeeOther: 0,
        onlineBankingFee: 0,
        smsBankingFee: 0,
        debitCardFee: 800,
        creditCardFee: 2000,
        nspbFee: 0,
        rtgsFee: 0,
        beftnFee: 0,
        checkbookFee: 0,
        statementFee: 0,
        otherCharges: 0,
        interestRate: 4.5,
      }
    ]
  },
  {
    id: 'ific-bank',
    bankName: 'IFIC Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1976,
    headquarters: 'Dhaka',
    website: 'https://www.ificbank.com.bd',
    totalBranches: 145,
    totalAtms: 380,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2500,
        accountMaintenanceFee: 50,
        atmFeeOwn: 0,
        atmFeeOther: 18,
        onlineBankingFee: 0,
        smsBankingFee: 28,
        debitCardFee: 350,
        creditCardFee: 900,
        nspbFee: 18,
        rtgsFee: 140,
        beftnFee: 9,
        checkbookFee: 90,
        statementFee: 45,
        otherCharges: 20,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'jamuna-bank',
    bankName: 'Jamuna Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 2001,
    headquarters: 'Dhaka',
    website: 'https://www.jamunabankbd.com',
    totalBranches: 160,
    totalAtms: 420,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2000,
        accountMaintenanceFee: 40,
        atmFeeOwn: 0,
        atmFeeOther: 16,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 300,
        creditCardFee: 800,
        nspbFee: 16,
        rtgsFee: 130,
        beftnFee: 8,
        checkbookFee: 80,
        statementFee: 40,
        otherCharges: 15,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'meghna-bank',
    bankName: 'Meghna Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 2013,
    headquarters: 'Dhaka',
    website: 'https://www.meghnabank.com.bd',
    totalBranches: 75,
    totalAtms: 180,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2000,
        accountMaintenanceFee: 40,
        atmFeeOwn: 0,
        atmFeeOther: 16,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 300,
        creditCardFee: 800,
        nspbFee: 16,
        rtgsFee: 130,
        beftnFee: 8,
        checkbookFee: 80,
        statementFee: 40,
        otherCharges: 15,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'mercantile-bank',
    bankName: 'Mercantile Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1999,
    headquarters: 'Dhaka',
    website: 'https://www.mblbd.com',
    totalBranches: 195,
    totalAtms: 500,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2500,
        accountMaintenanceFee: 50,
        atmFeeOwn: 0,
        atmFeeOther: 18,
        onlineBankingFee: 0,
        smsBankingFee: 28,
        debitCardFee: 350,
        creditCardFee: 900,
        nspbFee: 18,
        rtgsFee: 140,
        beftnFee: 9,
        checkbookFee: 90,
        statementFee: 45,
        otherCharges: 20,
        interestRate: 4.0,
      },
      {
        type: 'Senior Citizen',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 10,
        onlineBankingFee: 0,
        smsBankingFee: 15,
        debitCardFee: 200,
        creditCardFee: 500,
        nspbFee: 10,
        rtgsFee: 100,
        beftnFee: 5,
        checkbookFee: 50,
        statementFee: 25,
        otherCharges: 0,
        interestRate: 5.0,
      }
    ]
  },
  {
    id: 'midland-bank',
    bankName: 'Midland Bank Limited',
    bankType: 'Private Conventional',
    establishedYear: 2013,
    headquarters: 'Dhaka',
    website: 'https://www.midlandbank.com.bd',
    totalBranches: 65,
    totalAtms: 150,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2000,
        accountMaintenanceFee: 40,
        atmFeeOwn: 0,
        atmFeeOther: 16,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 300,
        creditCardFee: 800,
        nspbFee: 16,
        rtgsFee: 130,
        beftnFee: 8,
        checkbookFee: 80,
        statementFee: 40,
        otherCharges: 15,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'modhumoti-bank',
    bankName: 'Modhumoti Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 2013,
    headquarters: 'Dhaka',
    website: 'https://www.modhumotibank.com',
    totalBranches: 80,
    totalAtms: 200,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2000,
        accountMaintenanceFee: 40,
        atmFeeOwn: 0,
        atmFeeOther: 16,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 300,
        creditCardFee: 800,
        nspbFee: 16,
        rtgsFee: 130,
        beftnFee: 8,
        checkbookFee: 80,
        statementFee: 40,
        otherCharges: 15,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'mutual-trust-bank',
    bankName: 'Mutual Trust Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1999,
    headquarters: 'Dhaka',
    website: 'https://www.mutualtrustbank.com',
    totalBranches: 120,
    totalAtms: 320,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 3000,
        accountMaintenanceFee: 60,
        atmFeeOwn: 0,
        atmFeeOther: 20,
        onlineBankingFee: 0,
        smsBankingFee: 30,
        debitCardFee: 400,
        creditCardFee: 1000,
        nspbFee: 20,
        rtgsFee: 150,
        beftnFee: 10,
        checkbookFee: 100,
        statementFee: 50,
        otherCharges: 25,
        interestRate: 4.0,
      },
      {
        type: 'Student',
        minimumBalance: 500,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 10,
        onlineBankingFee: 0,
        smsBankingFee: 15,
        debitCardFee: 200,
        creditCardFee: 0,
        nspbFee: 10,
        rtgsFee: 80,
        beftnFee: 5,
        checkbookFee: 50,
        statementFee: 25,
        otherCharges: 0,
        interestRate: 4.5,
      }
    ]
  },
  {
    id: 'national-bank',
    bankName: 'National Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1983,
    headquarters: 'Dhaka',
    website: 'https://www.nblbd.com',
    totalBranches: 160,
    totalAtms: 420,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2500,
        accountMaintenanceFee: 50,
        atmFeeOwn: 0,
        atmFeeOther: 18,
        onlineBankingFee: 0,
        smsBankingFee: 28,
        debitCardFee: 350,
        creditCardFee: 900,
        nspbFee: 18,
        rtgsFee: 140,
        beftnFee: 9,
        checkbookFee: 90,
        statementFee: 45,
        otherCharges: 20,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'ncc-bank',
    bankName: 'National Credit & Commerce Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1985,
    headquarters: 'Dhaka',
    website: 'https://www.nccbank.com.bd',
    totalBranches: 120,
    totalAtms: 300,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2500,
        accountMaintenanceFee: 50,
        atmFeeOwn: 0,
        atmFeeOther: 18,
        onlineBankingFee: 0,
        smsBankingFee: 28,
        debitCardFee: 350,
        creditCardFee: 900,
        nspbFee: 18,
        rtgsFee: 140,
        beftnFee: 9,
        checkbookFee: 90,
        statementFee: 45,
        otherCharges: 20,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'nrb-bank',
    bankName: 'NRB Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 2013,
    headquarters: 'Dhaka',
    website: 'https://www.nrbbank.com',
    totalBranches: 45,
    totalAtms: 100,
    accountTypes: [
      {
        type: 'NRB',
        minimumBalance: 1000,
        accountMaintenanceFee: 75,
        atmFeeOwn: 0,
        atmFeeOther: 20,
        onlineBankingFee: 0,
        smsBankingFee: 35,
        debitCardFee: 500,
        creditCardFee: 1200,
        nspbFee: 25,
        rtgsFee: 175,
        beftnFee: 15,
        checkbookFee: 125,
        statementFee: 60,
        otherCharges: 40,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'nrbc-bank',
    bankName: 'NRBC Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 2013,
    headquarters: 'Dhaka',
    website: 'https://www.nrbcommercialbank.com',
    totalBranches: 55,
    totalAtms: 130,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2000,
        accountMaintenanceFee: 40,
        atmFeeOwn: 0,
        atmFeeOther: 16,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 300,
        creditCardFee: 800,
        nspbFee: 16,
        rtgsFee: 130,
        beftnFee: 8,
        checkbookFee: 80,
        statementFee: 40,
        otherCharges: 15,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'one-bank',
    bankName: 'One Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1999,
    headquarters: 'Dhaka',
    website: 'https://www.onebank.com.bd',
    totalBranches: 140,
    totalAtms: 360,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 3000,
        accountMaintenanceFee: 60,
        atmFeeOwn: 0,
        atmFeeOther: 20,
        onlineBankingFee: 0,
        smsBankingFee: 30,
        debitCardFee: 400,
        creditCardFee: 1000,
        nspbFee: 20,
        rtgsFee: 150,
        beftnFee: 10,
        checkbookFee: 100,
        statementFee: 50,
        otherCharges: 25,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'padma-bank',
    bankName: 'Padma Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 2013,
    headquarters: 'Dhaka',
    website: 'https://www.padmabank.com',
    totalBranches: 70,
    totalAtms: 170,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2000,
        accountMaintenanceFee: 40,
        atmFeeOwn: 0,
        atmFeeOther: 16,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 300,
        creditCardFee: 800,
        nspbFee: 16,
        rtgsFee: 130,
        beftnFee: 8,
        checkbookFee: 80,
        statementFee: 40,
        otherCharges: 15,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'prime-bank',
    bankName: 'Prime Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1995,
    headquarters: 'Dhaka',
    website: 'https://www.primebank.com.bd',
    totalBranches: 150,
    totalAtms: 350,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 5000,
        accountMaintenanceFee: 100,
        atmFeeOwn: 0,
        atmFeeOther: 25,
        onlineBankingFee: 0,
        smsBankingFee: 35,
        debitCardFee: 500,
        creditCardFee: 1200,
        nspbFee: 25,
        rtgsFee: 175,
        beftnFee: 15,
        checkbookFee: 125,
        statementFee: 60,
        otherCharges: 50,
        interestRate: 4.5,
      },
      {
        type: 'Women Account',
        minimumBalance: 2000,
        accountMaintenanceFee: 50,
        atmFeeOwn: 0,
        atmFeeOther: 15,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 300,
        creditCardFee: 800,
        nspbFee: 15,
        rtgsFee: 125,
        beftnFee: 8,
        checkbookFee: 75,
        statementFee: 40,
        otherCharges: 0,
        interestRate: 5.0,
      }
    ]
  },
  {
    id: 'pubali-bank',
    bankName: 'Pubali Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1959,
    headquarters: 'Dhaka',
    website: 'https://www.pubalibangla.com',
    totalBranches: 470,
    totalAtms: 1200,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2000,
        accountMaintenanceFee: 40,
        atmFeeOwn: 0,
        atmFeeOther: 16,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 300,
        creditCardFee: 800,
        nspbFee: 16,
        rtgsFee: 130,
        beftnFee: 8,
        checkbookFee: 80,
        statementFee: 40,
        otherCharges: 15,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'sbac-bank',
    bankName: 'SBAC Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 2013,
    headquarters: 'Dhaka',
    website: 'https://www.sbacbank.com',
    totalBranches: 60,
    totalAtms: 140,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2000,
        accountMaintenanceFee: 40,
        atmFeeOwn: 0,
        atmFeeOther: 16,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 300,
        creditCardFee: 800,
        nspbFee: 16,
        rtgsFee: 130,
        beftnFee: 8,
        checkbookFee: 80,
        statementFee: 40,
        otherCharges: 15,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'shimanto-bank',
    bankName: 'Shimanto Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 2013,
    headquarters: 'Dhaka',
    website: 'https://www.shimantobank.com',
    totalBranches: 50,
    totalAtms: 120,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2000,
        accountMaintenanceFee: 40,
        atmFeeOwn: 0,
        atmFeeOther: 16,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 300,
        creditCardFee: 800,
        nspbFee: 16,
        rtgsFee: 130,
        beftnFee: 8,
        checkbookFee: 80,
        statementFee: 40,
        otherCharges: 15,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'southeast-bank',
    bankName: 'Southeast Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1995,
    headquarters: 'Dhaka',
    website: 'https://www.southeastbank.com.bd',
    totalBranches: 155,
    totalAtms: 400,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2500,
        accountMaintenanceFee: 50,
        atmFeeOwn: 0,
        atmFeeOther: 18,
        onlineBankingFee: 0,
        smsBankingFee: 28,
        debitCardFee: 350,
        creditCardFee: 900,
        nspbFee: 18,
        rtgsFee: 140,
        beftnFee: 9,
        checkbookFee: 90,
        statementFee: 45,
        otherCharges: 20,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'the-premier-bank',
    bankName: 'The Premier Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1999,
    headquarters: 'Dhaka',
    website: 'https://www.premierbankltd.com',
    totalBranches: 90,
    totalAtms: 220,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2500,
        accountMaintenanceFee: 50,
        atmFeeOwn: 0,
        atmFeeOther: 18,
        onlineBankingFee: 0,
        smsBankingFee: 28,
        debitCardFee: 350,
        creditCardFee: 900,
        nspbFee: 18,
        rtgsFee: 140,
        beftnFee: 9,
        checkbookFee: 90,
        statementFee: 45,
        otherCharges: 20,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'trust-bank',
    bankName: 'Trust Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1999,
    headquarters: 'Dhaka',
    website: 'https://www.trustbank.com.bd',
    totalBranches: 100,
    totalAtms: 250,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2000,
        accountMaintenanceFee: 40,
        atmFeeOwn: 0,
        atmFeeOther: 16,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 300,
        creditCardFee: 800,
        nspbFee: 16,
        rtgsFee: 130,
        beftnFee: 8,
        checkbookFee: 80,
        statementFee: 40,
        otherCharges: 15,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'ucb-bank',
    bankName: 'United Commercial Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1983,
    headquarters: 'Dhaka',
    website: 'https://www.ucb.com.bd',
    totalBranches: 180,
    totalAtms: 450,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2500,
        accountMaintenanceFee: 50,
        atmFeeOwn: 0,
        atmFeeOther: 18,
        onlineBankingFee: 0,
        smsBankingFee: 28,
        debitCardFee: 350,
        creditCardFee: 900,
        nspbFee: 18,
        rtgsFee: 140,
        beftnFee: 9,
        checkbookFee: 90,
        statementFee: 45,
        otherCharges: 20,
        interestRate: 4.0,
      }
    ]
  },
  {
    id: 'uttara-bank',
    bankName: 'Uttara Bank PLC',
    bankType: 'Private Conventional',
    establishedYear: 1965,
    headquarters: 'Dhaka',
    website: 'https://www.uttarabank-bd.com',
    totalBranches: 220,
    totalAtms: 550,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 2000,
        accountMaintenanceFee: 40,
        atmFeeOwn: 0,
        atmFeeOther: 16,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 300,
        creditCardFee: 800,
        nspbFee: 16,
        rtgsFee: 130,
        beftnFee: 8,
        checkbookFee: 80,
        statementFee: 40,
        otherCharges: 15,
        interestRate: 4.0,
      }
    ]
  },
  // Islamic Banks
  {
    id: 'al-arafah-islami-bank',
    bankName: 'Al-Arafah Islami Bank PLC',
    bankType: 'Islamic Bank',
    establishedYear: 1995,
    headquarters: 'Dhaka',
    website: 'https://www.al-arafahbank.com',
    totalBranches: 200,
    totalAtms: 500,
    accountTypes: [
      {
        type: 'Mudaraba Savings',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 12,
        onlineBankingFee: 0,
        smsBankingFee: 20,
        debitCardFee: 300,
        creditCardFee: 0,
        nspbFee: 15,
        rtgsFee: 120,
        beftnFee: 8,
        checkbookFee: 60,
        statementFee: 25,
        otherCharges: 0,
        interestRate: 0,
      },
      {
        type: 'Al-Wadiah Current',
        minimumBalance: 5000,
        accountMaintenanceFee: 50,
        atmFeeOwn: 0,
        atmFeeOther: 15,
        onlineBankingFee: 0,
        smsBankingFee: 25,
        debitCardFee: 400,
        creditCardFee: 0,
        nspbFee: 20,
        rtgsFee: 150,
        beftnFee: 10,
        checkbookFee: 80,
        statementFee: 35,
        otherCharges: 25,
        interestRate: 0,
      }
    ]
  },
  {
    id: 'export-import-bank',
    bankName: 'Export Import Bank of Bangladesh PLC',
    bankType: 'Islamic Bank',
    establishedYear: 1999,
    headquarters: 'Dhaka',
    website: 'https://www.eximbankbd.com',
    totalBranches: 155,
    totalAtms: 400,
    accountTypes: [
      {
        type: 'Mudaraba Savings',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 12,
        onlineBankingFee: 0,
        smsBankingFee: 20,
        debitCardFee: 300,
        creditCardFee: 0,
        nspbFee: 15,
        rtgsFee: 120,
        beftnFee: 8,
        checkbookFee: 60,
        statementFee: 25,
        otherCharges: 0,
        interestRate: 0,
      }
    ]
  },
  {
    id: 'first-security-islami-bank',
    bankName: 'First Security Islami Bank PLC',
    bankType: 'Islamic Bank',
    establishedYear: 1999,
    headquarters: 'Dhaka',
    website: 'https://www.fsiblbd.com',
    totalBranches: 180,
    totalAtms: 450,
    accountTypes: [
      {
        type: 'Mudaraba Savings',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 12,
        onlineBankingFee: 0,
        smsBankingFee: 20,
        debitCardFee: 300,
        creditCardFee: 0,
        nspbFee: 15,
        rtgsFee: 120,
        beftnFee: 8,
        checkbookFee: 60,
        statementFee: 25,
        otherCharges: 0,
        interestRate: 0,
      }
    ]
  },
  {
    id: 'global-islami-bank',
    bankName: 'Global Islami Bank PLC',
    bankType: 'Islamic Bank',
    establishedYear: 2013,
    headquarters: 'Dhaka',
    website: 'https://www.globalislamibank.com',
    totalBranches: 80,
    totalAtms: 200,
    accountTypes: [
      {
        type: 'Mudaraba Savings',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 12,
        onlineBankingFee: 0,
        smsBankingFee: 20,
        debitCardFee: 300,
        creditCardFee: 0,
        nspbFee: 15,
        rtgsFee: 120,
        beftnFee: 8,
        checkbookFee: 60,
        statementFee: 25,
        otherCharges: 0,
        interestRate: 0,
      }
    ]
  },
  {
    id: 'icb-islamic-bank',
    bankName: 'ICB Islamic Bank Ltd.',
    bankType: 'Islamic Bank',
    establishedYear: 2008,
    headquarters: 'Dhaka',
    website: 'https://www.icbislamicbank.com',
    totalBranches: 70,
    totalAtms: 180,
    accountTypes: [
      {
        type: 'Mudaraba Savings',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 12,
        onlineBankingFee: 0,
        smsBankingFee: 20,
        debitCardFee: 300,
        creditCardFee: 0,
        nspbFee: 15,
        rtgsFee: 120,
        beftnFee: 8,
        checkbookFee: 60,
        statementFee: 25,
        otherCharges: 0,
        interestRate: 0,
      }
    ]
  },
  {
    id: 'islami-bank',
    bankName: 'Islami Bank Bangladesh PLC',
    bankType: 'Islamic Bank',
    establishedYear: 1983,
    headquarters: 'Dhaka',
    website: 'https://www.islamibankbd.com',
    totalBranches: 370,
    totalAtms: 1200,
    accountTypes: [
      {
        type: 'Mudaraba Savings',
        minimumBalance: 500,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 12,
        onlineBankingFee: 0,
        smsBankingFee: 20,
        debitCardFee: 300,
        creditCardFee: 0,
        nspbFee: 15,
        rtgsFee: 120,
        beftnFee: 8,
        checkbookFee: 60,
        statementFee: 25,
        otherCharges: 0,
        interestRate: 0,
      },
      {
        type: 'Student',
        minimumBalance: 100,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 5,
        onlineBankingFee: 0,
        smsBankingFee: 10,
        debitCardFee: 150,
        creditCardFee: 0,
        nspbFee: 8,
        rtgsFee: 60,
        beftnFee: 4,
        checkbookFee: 30,
        statementFee: 15,
        otherCharges: 0,
        interestRate: 0,
      }
    ]
  },
  {
    id: 'shahjalal-islami-bank',
    bankName: 'Shahjalal Islami Bank PLC',
    bankType: 'Islamic Bank',
    establishedYear: 2001,
    headquarters: 'Dhaka',
    website: 'https://www.sjiblbd.com',
    totalBranches: 190,
    totalAtms: 480,
    accountTypes: [
      {
        type: 'Mudaraba Savings',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 12,
        onlineBankingFee: 0,
        smsBankingFee: 20,
        debitCardFee: 300,
        creditCardFee: 0,
        nspbFee: 15,
        rtgsFee: 120,
        beftnFee: 8,
        checkbookFee: 60,
        statementFee: 25,
        otherCharges: 0,
        interestRate: 0,
      }
    ]
  },
  {
    id: 'social-islami-bank',
    bankName: 'Social Islami Bank PLC',
    bankType: 'Islamic Bank',
    establishedYear: 1995,
    headquarters: 'Dhaka',
    website: 'https://www.siblbd.com',
    totalBranches: 170,
    totalAtms: 420,
    accountTypes: [
      {
        type: 'Mudaraba Savings',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 12,
        onlineBankingFee: 0,
        smsBankingFee: 20,
        debitCardFee: 300,
        creditCardFee: 0,
        nspbFee: 15,
        rtgsFee: 120,
        beftnFee: 8,
        checkbookFee: 60,
        statementFee: 25,
        otherCharges: 0,
        interestRate: 0,
      }
    ]
  },
  {
    id: 'standard-bank',
    bankName: 'Standard Bank PLC',
    bankType: 'Islamic Bank',
    establishedYear: 1999,
    headquarters: 'Dhaka',
    website: 'https://www.standardbankbd.com',
    totalBranches: 140,
    totalAtms: 350,
    accountTypes: [
      {
        type: 'Mudaraba Savings',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 12,
        onlineBankingFee: 0,
        smsBankingFee: 20,
        debitCardFee: 300,
        creditCardFee: 0,
        nspbFee: 15,
        rtgsFee: 120,
        beftnFee: 8,
        checkbookFee: 60,
        statementFee: 25,
        otherCharges: 0,
        interestRate: 0,
      }
    ]
  },
  {
    id: 'union-bank',
    bankName: 'Union Bank PLC',
    bankType: 'Islamic Bank',
    establishedYear: 2013,
    headquarters: 'Dhaka',
    website: 'https://www.unionbank.com.bd',
    totalBranches: 90,
    totalAtms: 220,
    accountTypes: [
      {
        type: 'Mudaraba Savings',
        minimumBalance: 1000,
        accountMaintenanceFee: 0,
        atmFeeOwn: 0,
        atmFeeOther: 12,
        onlineBankingFee: 0,
        smsBankingFee: 20,
        debitCardFee: 300,
        creditCardFee: 0,
        nspbFee: 15,
        rtgsFee: 120,
        beftnFee: 8,
        checkbookFee: 60,
        statementFee: 25,
        otherCharges: 0,
        interestRate: 0,
      }
    ]
  },
  // Foreign Banks
  {
    id: 'bank-al-falah',
    bankName: 'Bank Al-Falah Limited',
    bankType: 'Foreign Commercial Bank',
    establishedYear: 2009,
    headquarters: 'Karachi, Pakistan',
    website: 'https://www.bankalfalah.com',
    totalBranches: 20,
    totalAtms: 50,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 10000,
        accountMaintenanceFee: 200,
        atmFeeOwn: 0,
        atmFeeOther: 40,
        onlineBankingFee: 0,
        smsBankingFee: 40,
        debitCardFee: 800,
        creditCardFee: 1800,
        nspbFee: 40,
        rtgsFee: 200,
        beftnFee: 20,
        checkbookFee: 200,
        statementFee: 100,
        otherCharges: 150,
        interestRate: 4.5,
      }
    ]
  },
  {
    id: 'citibank',
    bankName: 'Citibank N.A',
    bankType: 'Foreign Commercial Bank',
    establishedYear: 1987,
    headquarters: 'New York, USA',
    website: 'https://www.citibank.com.bd',
    totalBranches: 5,
    totalAtms: 30,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 50000,
        accountMaintenanceFee: 500,
        atmFeeOwn: 0,
        atmFeeOther: 100,
        onlineBankingFee: 0,
        smsBankingFee: 100,
        debitCardFee: 2000,
        creditCardFee: 5000,
        nspbFee: 100,
        rtgsFee: 500,
        beftnFee: 50,
        checkbookFee: 500,
        statementFee: 250,
        otherCharges: 500,
        interestRate: 5.5,
      }
    ]
  },
  {
    id: 'commercial-bank-ceylon',
    bankName: 'Commercial Bank of Ceylon Limited',
    bankType: 'Foreign Commercial Bank',
    establishedYear: 2003,
    headquarters: 'Colombo, Sri Lanka',
    website: 'https://www.combank.lk',
    totalBranches: 15,
    totalAtms: 40,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 15000,
        accountMaintenanceFee: 250,
        atmFeeOwn: 0,
        atmFeeOther: 50,
        onlineBankingFee: 0,
        smsBankingFee: 50,
        debitCardFee: 1000,
        creditCardFee: 2500,
        nspbFee: 50,
        rtgsFee: 300,
        beftnFee: 25,
        checkbookFee: 300,
        statementFee: 150,
        otherCharges: 200,
        interestRate: 5.0,
      }
    ]
  },
  {
    id: 'habib-bank',
    bankName: 'Habib Bank Ltd.',
    bankType: 'Foreign Commercial Bank',
    establishedYear: 1976,
    headquarters: 'Karachi, Pakistan',
    website: 'https://www.hbl.com',
    totalBranches: 18,
    totalAtms: 45,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 12000,
        accountMaintenanceFee: 220,
        atmFeeOwn: 0,
        atmFeeOther: 45,
        onlineBankingFee: 0,
        smsBankingFee: 45,
        debitCardFee: 900,
        creditCardFee: 2200,
        nspbFee: 45,
        rtgsFee: 250,
        beftnFee: 22,
        checkbookFee: 250,
        statementFee: 120,
        otherCharges: 180,
        interestRate: 4.8,
      }
    ]
  },
  {
    id: 'national-bank-pakistan',
    bankName: 'National Bank of Pakistan',
    bankType: 'Foreign Commercial Bank',
    establishedYear: 1973,
    headquarters: 'Karachi, Pakistan',
    website: 'https://www.nbp.com.pk',
    totalBranches: 12,
    totalAtms: 35,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 10000,
        accountMaintenanceFee: 200,
        atmFeeOwn: 0,
        atmFeeOther: 40,
        onlineBankingFee: 0,
        smsBankingFee: 40,
        debitCardFee: 800,
        creditCardFee: 2000,
        nspbFee: 40,
        rtgsFee: 200,
        beftnFee: 20,
        checkbookFee: 200,
        statementFee: 100,
        otherCharges: 150,
        interestRate: 4.5,
      }
    ]
  },
  {
    id: 'standard-chartered',
    bankName: 'Standard Chartered Bank',
    bankType: 'Foreign Commercial Bank',
    establishedYear: 1948,
    headquarters: 'London, UK',
    website: 'https://www.sc.com/bd',
    totalBranches: 25,
    totalAtms: 150,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 25000,
        accountMaintenanceFee: 300,
        atmFeeOwn: 0,
        atmFeeOther: 50,
        onlineBankingFee: 0,
        smsBankingFee: 50,
        debitCardFee: 1000,
        creditCardFee: 2000,
        nspbFee: 50,
        rtgsFee: 250,
        beftnFee: 25,
        checkbookFee: 300,
        statementFee: 150,
        otherCharges: 200,
        interestRate: 5.0,
      }
    ]
  },
  {
    id: 'state-bank-india',
    bankName: 'State Bank of India',
    bankType: 'Foreign Commercial Bank',
    establishedYear: 1973,
    headquarters: 'Mumbai, India',
    website: 'https://www.sbi.co.in',
    totalBranches: 8,
    totalAtms: 25,
    accountTypes: [
      {
        type: 'Savings',
        minimumBalance: 8000,
        accountMaintenanceFee: 150,
        atmFeeOwn: 0,
        atmFeeOther: 35,
        onlineBankingFee: 0,
        smsBankingFee: 35,
        debitCardFee: 700,
        creditCardFee: 1500,
        nspbFee: 35,
        rtgsFee: 180,
        beftnFee: 18,
        checkbookFee: 180,
        statementFee: 90,
        otherCharges: 120,
        interestRate: 4.2,
      }
    ]
  },
    {
      id: 'hsbc',
      bankName: 'The Hong Kong and Shanghai Banking Corporation Ltd.',
      bankType: 'Foreign Commercial Bank',
      establishedYear: 1996,
      headquarters: 'Hong Kong',
      website: 'https://www.hsbc.com.bd',
      totalBranches: 15,
      totalAtms: 80,
      accountTypes: [
        {
          type: 'Savings',
          minimumBalance: 30000,
          accountMaintenanceFee: 400,
          atmFeeOwn: 0,
          atmFeeOther: 60,
          onlineBankingFee: 0,
          smsBankingFee: 60,
          debitCardFee: 1200,
          creditCardFee: 3000,
          nspbFee: 60,
          rtgsFee: 300,
          beftnFee: 30,
          checkbookFee: 400,
          statementFee: 200,
          otherCharges: 300,
          interestRate: 5.2,
        }
      ]
    }
  ];

async function seedBank(bankInfo) {
  try {
    // Insert bank data
    await sql`
      INSERT INTO banks (
        id, bank_name, bank_type, established_year, 
        headquarters, website, total_branches, total_atms
      ) VALUES (
        ${bankInfo.id}, ${bankInfo.bankName}, ${bankInfo.bankType}, 
        ${bankInfo.establishedYear}, ${bankInfo.headquarters}, 
        ${bankInfo.website}, ${bankInfo.totalBranches}, ${bankInfo.totalAtms}
      )
      ON CONFLICT (id) DO UPDATE SET
        bank_name = EXCLUDED.bank_name,
        bank_type = EXCLUDED.bank_type,
        established_year = EXCLUDED.established_year,
        headquarters = EXCLUDED.headquarters,
        website = EXCLUDED.website,
        total_branches = EXCLUDED.total_branches,
        total_atms = EXCLUDED.total_atms,
        updated_at = CURRENT_TIMESTAMP
    `;

    // Insert account types
    for (const accountType of bankInfo.accountTypes) {
      await sql`
        INSERT INTO account_types (
          bank_id, account_type, minimum_balance, account_maintenance_fee,
          atm_fee_own, atm_fee_other, online_banking_fee, sms_banking_fee,
          debit_card_fee, credit_card_fee, nspb_fee, rtgs_fee, beftn_fee,
          checkbook_fee, statement_fee, other_charges, interest_rate
        ) VALUES (
          ${bankInfo.id}, ${accountType.type}, ${accountType.minimumBalance},
          ${accountType.accountMaintenanceFee}, ${accountType.atmFeeOwn},
          ${accountType.atmFeeOther}, ${accountType.onlineBankingFee},
          ${accountType.smsBankingFee}, ${accountType.debitCardFee},
          ${accountType.creditCardFee}, ${accountType.nspbFee},
          ${accountType.rtgsFee}, ${accountType.beftnFee},
          ${accountType.checkbookFee}, ${accountType.statementFee},
          ${accountType.otherCharges}, ${accountType.interestRate}
        )
      `;
    }

    console.log(`Successfully seeded bank: ${bankInfo.bankName}`);
  } catch (error) {
    console.error(`Error seeding bank ${bankInfo.bankName}:`, error);
  }
}

// Function to seed multiple banks
async function seedAllBanks(banksArray) {
  for (const bank of banksArray) {
    await seedBank(bank);
  }
}

export { seedBank, seedAllBanks, bankData };
